# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ibis_badge',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/ibis_badge',
                'lib_path': 'ibis_badge'},
  'syms': {'ibis_badge.core': {'ibis_badge.core.foo': ('core.html#foo', 'ibis_badge/core.py')}}}
